# Generated by Django 5.1.4 on 2025-01-02 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, verbose_name='Ismi')),
                ('last_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Familiyasi')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Telefon raqami')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan yili")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Viloyat')),
                ('state', models.CharField(max_length=100, verbose_name='Shahar')),
                ('address_line', models.CharField(max_length=255, verbose_name='Manzil')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Pochta indeksi')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name="Telefon raqam(qo'shimcha)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customer.customer', verbose_name='Mijoz')),
            ],
            options={
                'verbose_name': 'Manzil',
                'verbose_name_plural': 'Manzillar',
                'db_table': 'address',
                'ordering': ['-created_at'],
            },
        ),
    ]
