# Generated by Django 5.1.4 on 2025-01-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Mijoz', 'verbose_name_plural': 'Mijozlar'},
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Andijon', 'Andijon'), ('Buxoro', 'Buxoro'), ('Farg‘ona', 'Farg‘ona'), ('Jizzax', 'Jizzax'), ('Xorazm', 'Xorazm'), ('Namangan', 'Namangan'), ('Navoiy', 'Navoiy'), ('Qashqadaryo', 'Qashqadaryo'), ('Qoraqalpog‘iston', 'Qoraqalpog‘iston'), ('Samarqand', 'Samarqand'), ('Sirdaryo', 'Sirdaryo'), ('Surxondaryo', 'Surxondaryo'), ('Toshkent', 'Toshkent'), ('Toshkent shahar', 'Toshkent shahar')], max_length=100, verbose_name='Viloyat'),
        ),
    ]
