# Generated by Django 5.1.4 on 2025-01-08 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_address_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='customer',
        ),
    ]
