# Generated by Django 5.1.4 on 2025-01-03 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_color_size_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.color', verbose_name='rangi'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.size', verbose_name="o'lchami"),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=200, verbose_name='nomi'),
        ),
    ]
