# Generated by Django 5.1.4 on 2025-01-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_color_product_size_alter_size_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='nomi'),
        ),
    ]
