# Generated by Django 5.1.4 on 2025-01-03 08:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '📦 Qabul qilindi'), ('shipped', "🚚 Yetkazilmoqda (Yo'lda)"), ('delivered', 'Yetkazib berildi✅'), ('canceled', '❌ Bekor qilindi')], default='pending', max_length=20),
        ),
    ]
