# Generated by Django 5.1.4 on 2025-01-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderitem_created_at_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name="To'loq qildimi?"),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('thinking', "🤔 O'ylab ko'radi"), ('pending', '📦 Qabul qilindi'), ('shipped', "🚚 Yetkazilmoqda (Yo'lda)"), ('delivered', 'Yetkazib berildi✅'), ('canceled', '❌ Bekor qilindi')], default='pending', max_length=20),
        ),
    ]
