# Generated by Django 5.1.4 on 2025-01-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_is_paid_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Tavsif'),
        ),
    ]
