# Generated by Django 5.1.4 on 2025-01-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', '💵 Naqt'), ('card', '💳 Click'), ('mail', '📨 Pochta orqali')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('get_tomorrow', '🤥 Keyin oladi'), ('pending', '📦 Qabul qilindi'), ('shipped', "🚚 Yetkazilmoqda (Yo'lda)"), ('delivered', 'Yetkazib berildi✅'), ('canceled', '❌ Bekor qilindi')], default='pending', max_length=20),
        ),
    ]
