# Generated by Django 5.1.4 on 2025-01-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prepayment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name="Oldindan to'lov summasi"),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name="To'lov qildimi?"),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('get_tomorrow', '🤥 Keyin oladi'), ('hold', '🗳 Zakazga'), ('pending', '📦 Qabul qilindi'), ('shipped', "🚚 Yetkazilmoqda (Yo'lda)"), ('delivered', 'Yetkazib berildi✅'), ('canceled', '❌ Bekor qilindi')], default='pending', max_length=20),
        ),
    ]
