# Generated by Django 5.1.4 on 2025-01-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='orders/', verbose_name='Rasm'),
        ),
    ]
