# Generated by Django 5.1.4 on 2025-01-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_order_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('get_tomorrow', '🤥 Keyin oladi'), ('hold', '🗳 Zakazga'), ('pending', '📦 Qabul qilindi'), ('ready_delivery', '🛍 Dastavkaga Tayyor'), ('shipped', "🚚 Yetkazilmoqda (Yo'lda)"), ('delivered', 'Yetkazib berildi✅'), ('canceled', '❌ Bekor qilindi')], default='pending', max_length=20),
        ),
    ]
