# Generated by Django 5.1.4 on 2025-01-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Buyurtma soni'),
        ),
    ]
